### ISSUE TITLE
How to update public folder?

### ISSUE THREAD

**Issue by RicardoGabriel** [hollina/template-job-market-website#1]
Hi Alex,

Thank you so much for such a detailed explanation regarding building a website.
I have one specific question - how can we update the public folder? Currently, after making all the changes in all the other folders, the public folder does not update by itself, and thus, when building the website (dragging the public folder to netlify) always yield the same standard website for the job market candidate.

Thank you for your help!

**Comment by RicardoGabriel** [comment]
So, I was able to understand the issue. One needs to run the command "blogdown::hugo_build()" to update the public folder.
Thank you once again.

**Comment by hollina** [comment]
Ah! Sorry that I left this part off or it was created in an earlier step. I will check it out and add it to the guide. Thanks for finding this!
