### ISSUE TITLE
Public the website

### ISSUE THREAD

**Issue by thuydoanvn** [hollina/template-job-market-website#2]
Thanks for the detailed instruction at https://hollina.github.io/make-a-job-market-website.html

I've done customizing the site and it looks nicely in R-studio. The problem is that the 'public' folder is not updated even though I did all five steps in the publish section (blogdown::serve_site() and blogdown::stop_server()). The published website on Netlify still appears exactly the same as the template. 

Do I need to manually copy all the components into the public folder or is there any command to automatically update the public folder?

Thanks,
Thuy

**Comment by hollina** [comment]
Hi Thuy, 

run the command `blogdown::hugo_build()`. This will build the correct public folder. Sorry this was missing.

**Comment by hollina** [comment]
I've updated the website now to reflect this. Thanks to you (and a few others) for pointing this out. Sorry I forgot to update the guide after it was pointed out last time!

**Comment by thuydoanvn** [comment]
Great, it works now. Thank you!
