### ISSUE TITLE
How to disable the title link on my working papers as well as publications? 

### ISSUE THREAD

**Issue by linjing-s** [hollina/template-job-market-website#3]
Thanks for your sharing and I have built my first homepage. However, every title of all my working papers and publications has a link which opens a page showing roughly the same information as before, and this is really annoying. 

I tried many ways suggested by others (for example, a [discussion](https://github.com/wowchemy/wowchemy-hugo-themes/issues/982) here), and they all fail to remove the title link. 

Do you have any idea how to achieve this?

**Comment by hollina** [comment]
I'm not sure about this sorry! I use a different theme for my own webpage and it took a bunch of tinkering about to get the style that I desired. You can simply edit the html code after it's created (in the public folder) as a not very simple, but guaranteed to work solution. For something a touch more robust, you could fork the academic repo and edit the html code. I did a lot of stuff like this (https://github.com/wowchemy/wowchemy-hugo-themes/issues/982#issuecomment-492781845) in my modification of the theme I'm using. However, if you already tried that, I'm not sure what else to do. Maybe try another theme? Sorry I'm not too much help here.
